#!/bin/bash

sleep 1

. "/home/lasanjin/.scripts/bat"

case "$1" in
"m")
    batl="Mouse: "$(bat $1)
    ;;
"k")
    batl="Keyboard: "$(bat $1)
    ;;
*)
    batl="Uknown"
    ;;
esac

# display bat level if <= 10 %
if [ $(echo $batl | sed 's/[^0-9]*//g') -le 10 ]; then
    sudo -u lasanjin \
        DISPLAY=:0 \
        DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send \
        $batl
fi
