#!/bin/bash

sleep 1

# card0-DP-1, card0-DP-2
read STATUS </sys/class/drm/card0/card0-DP-1/status # connected/disconnected

case "$STATUS" in
"connected")
    bluetooth on
    ;;
*)
    bluetooth off
    ;;
esac
