#!/bin/bash

#battery status
bat() {
    case "$1" in
    "m")
        param="mouse_dev"
        ;;
    "k")
        param="mouse_hid"
        ;;
    *)
        param="BAT"
        ;;
    esac

    upower -i $(upower -e | grep $param) | grep 'time\|percentage' | sed -e 's/[^0-9]*//'
}
