#!/bin/bash

ddate() {
    case "$1" in
    "+" | "-") # date ndays from date/today
        date -d "$2 $1$3 days" +"%y-%m-%d"
        ;;
    "d") # days between <start_date> and <end_date>
        from=$(date --date="$2" +%s)
        to=$(date --date="$3" +%s)

        echo $((($from - $to) / (60 * 60 * 24)))
        ;;
    *)
        echo "Usage: ddate +|- [date] <number_of_days> | d <start_date> <end_date>"
        ;;

    esac
}
