#!/bin/bash

findpdf() {
    if ! [ $# -ge 2 ]; then
        usage
        return
    fi

    if [ $# -eq 4 ]; then
        sudo find $1 -iname '*.pdf' -exec pdfgrep -H -n -i "\b$2\s$3\W+(\w+\W+){0,5}$4\b" {} +
    elif [ $# -eq 3 ]; then
        sudo find $1 -iname '*.pdf' -exec pdfgrep -H -n -i "\b$2\W+(\w+\W+){1,5}$3\b" {} + # "\b$2\W+(\w+\W+){1,5}$3|$3\W+(\w+\W+){1,5}$2\b"
    else
        sudo find $1 -iname '*.pdf' -exec pdfgrep -H -n -i "\b$2\b" {} +
    fi
}

usage() {
    echo 'search in pdf-files in dir ($1):'
    echo -e ' · word1 ($2) + ' ' + word2 ($3) near word3 ($4)'
    echo -e ' · word1 ($2) and word2 ($3) near each other'
    echo -e ' · string ($2)'
}
