#!/bin/bash

#search fname ($1) in dir ($2) with maxdepth ($3)
# ${@:X} params, e.g. -delete
findf() {
    if [ -z "$1" ]; then
        echo "Invalid input"
        return
    fi

    case "$2" in
    ".")
        sudo find . -maxdepth 1 -iname "*$1*" ${@:3}
        ;;
    *)
        if [[ "$2" == *"/"* ]]; then
            fdir $@
        else
            sudo find -iname "*$1*" ${@:2}
        fi
        ;;
    esac
}

fdir() {
    case "$3" in
    ".")
        sudo find $2 -maxdepth 1 -iname "*$1*" ${@:3}
        ;;

    *)
        if [[ "$3" =~ ^[0-9]+$ ]] && [ $3 -ge 1 ]; then
            sudo find $2 -maxdepth $3 -iname "*$1*" ${@:4}
        else
            sudo find $2 -iname "*$1*" ${@:3}
        fi
        ;;
    esac
}
