#!/bin/bash

# cat all files $1 in current dir
list() {
    BOLD='\e[1m'
    BLUE='\e[94m'
    DEFAULT='\e[0m'

    len=$(tput cols)
    fs=$(find . -maxdepth 1 -type f -iname "*$1*" | sort -V)

    for f in $fs; do
        name=$(echo $f | sed 's@.*/@@')
        echo -e ${BLUE}${BOLD}${name^^}${DEFAULT}
        cat $f
        printf "%${len}s\n\n" | tr " " =
    done
}
