#!/bin/bash

# cat all files $1 in current dir
list() {
    BOLD='\e[1m'
    BLUE='\e[94m'
    DEFAULT='\e[0m'

    fs=$(find . -maxdepth 1 -type f -iname "*$1*")

    for f in $fs; do
        echo -e ${BLUE}${BOLD}${f^^}${DEFAULT}
        cat $f
        printf "%$(tput cols)s\n\n" | tr " " =
    done
}
