#!/bin/bash

#change mouse sensitivity
mouse() {
    local re='^[+-]?[0-9]+([.][0-9]+)?$'
    if [[ "$1" =~ $re ]] && [ $1 -ge -2 ] && [ $1 -le 2 ]; then
        local id=$(xinput |
            grep --color=never "$mouse.*pointer" |
            sed -e 's/.*id=//' |
            sed 's/\s.*$//')
        xinput --set-prop $id "libinput Accel Speed" $1
    fi
}
