#!/bin/bash

#create & open note-yyyy-mm-dd-seq#
note() {
    # uniq=$(date '+%N')
    case "$1" in
    "md")
        dir=$notesdir'mdnotes/'
        ;;
    *)
        dir=$notesdir
        ;;
    esac

    date=$(date '+%F')
    f='note-'$date'-'
    fs=$dir$f*

    if ls -U $fs &>/dev/null; then
        seq=$(ls $fs |
            sort -n -t - -k 2 |
            tail -1 |
            cut -f1 -d"." |
            sed 's/.*\-//')
        ((seq++))
    else
        seq='1'
    fi

    path=$dir$f$seq

    case "$1" in
    "md")
        touch $path'.md'
        echo -e '# '$date'\n' >$path'.md'
        code -n $path'.md'
        ;;
    *)
        touch $path
        echo -e $date'\n' >$path
        o $path
        ;;
    esac
}
