#!/bin/bash

#amazing pi calc
pi() {
    if [[ "$1" =~ ^[0-9]+$ ]] && [ $1 -ge 2 ]; then
        python -c "from mpmath import mp; mp.dps=$1; print mp.pi"
    else
        echo "pi [1...]"
        return 0
    fi
}
