#!/bin/bash

#uninstall app
remove() {
    read -p "DELETE \"$1\" ? (Y/N): " ans

    case ${ans:0:1} in
    y | Y)
        # use srm (secure-delete) for proper purge
        sudo apt-get --purge remove $1
        sudo apt-get autoremove
        sudo apt-get autoclean
        sudo apt-get clean
        echo OK
        ;;
    *)
        echo ABORT
        ;;
    esac
}
