#!/bin/bash

#copy bash files, scripts, rules etc.
save() {
    sudo cp -rf ~/.bash_aliases "$REPDIR"dotfiles
    sudo cp -rf ~/.scripts/* "$REPDIR"dotfiles/.scripts/
    # sudo cp -rf ~/.rules/* "$REPDIR"dotfiles/.rules/
    sudo cp -rf ~/.plugs/* "$REPDIR"dotfiles/.plugs/
    echo OK
}
