#!/bin/bash

#volume: main sound & HDMI
sound() {
    usage="Usage: sound [on | off | 1..150]"

    case $1 in
    *[0-9]*)
        if [ $1 -ge 0 ] && [ $1 -le 150 ]; then
            amixer -q -D pulse sset Master $1%
        else
            echo $usage
        fi
        ;;
    'on')
        amixer -q -D pulse sset Master on
        ;;
    'off')
        amixer -q -D pulse sset Master off
        ;;
    '-h' | '--help')
        echo $usage
        ;;
    *)
        amixer -D pulse get Master | awk -F 'Left:|[][]' 'BEGIN {RS=""}{ print $3 }'
        ;;
    esac
}
